### ISSUE TITLE
Configure the attrs.xml to use 'sp' and 'dp' in xml size fields

### ISSUE THREAD

**Issue by krharsh17** [krharsh17/barview-android#1]

**Comment by shreyasrivastava936** [comment]
Hi! I would like to work on this issue. please assign this task to me for GSSoC'20.

**Comment by krharsh17** [comment]
Sure

**Comment by Medhavi-16** [comment]
I would like to work on this.

**Comment by vinay2214** [comment]
I would like to work on this

**Comment by meghaa105** [comment]
Can you please assign this to me?

**Comment by krharsh17** [comment]
@Medhavi-16 what's the status on this?

**Comment by krharsh17** [comment]
@shreyasrivastava936 What's the status on this?

**Comment by krharsh17** [comment]
Its been too long since there's been activity on this, so I'm gonna have to unassign @shreyasrivastava936

**Comment by parthsharma07** [comment]
Please assign it to me. I would like to work on this.
