### ISSUE TITLE
[BUG] Configure the width of the bars so that they fit inside the screen even at max length

### ISSUE THREAD

**Issue by krharsh17** [krharsh17/barview-android#12]
Currently, on some screens, the width of the bar exceeds the screen width, due to which the values are not visible on the screen

**Comment by DarthBenro008** [comment]
I would like to work on this.

**Comment by krharsh17** [comment]
Alright

**Comment by VaishSiddharth** [comment]
@DarthBenro008 Still working on this?? @krharsh17  Can I work on this if @DarthBenro008 allows?

**Comment by DarthBenro008** [comment]
@VaishSiddharth i am working on this and i will be submitting the PR after March 1 2020 , as this project is included in GSSoC 20

**Comment by 8426988382** [comment]
@DarthBenro008  can i work on this?
