### ISSUE TITLE
Create an option to set the corner radius of the value tooltips

### ISSUE THREAD

**Issue by krharsh17** [krharsh17/barview-android#13]

**Comment by parthsharma07** [comment]
I want to work on this issue. Please assign it to me.

**Comment by krharsh17** [comment]
This is for phase 2. It will be assigned once phase 1 is complete.

**Comment by krharsh17** [comment]
@parthsharma07 please submit a PR as soon as possible

**Comment by parthsharma07** [comment]
I have started working on this issue and it will take a few days for me to submit a PR on this issue. Please Consider it.

**Comment by krharsh17** [comment]
Alright
