### ISSUE TITLE
Allow passing an optional color hex, to generate random colors similar to it

### ISSUE THREAD

**Issue by krharsh17** [krharsh17/barview-android#2]

**Comment by VibhorChinda** [comment]
Hii @krharsh17 i want to work on this issue. Can you please assign this to me.

**Comment by krharsh17** [comment]
Sure

**Comment by VibhorChinda** [comment]
@krharsh17 can you please provide an explanation of exactly what this enhancement talks about ?
Like what i understood after reading the code for library is that it is generating background colour randomly.

Do you want that i should provide a new field in the barModel named as optional background colour ??

And if yes then when should be that colour be used ?? 

Some help would be great.

**Comment by krharsh17** [comment]
@VibhorChinda You have to make an additional field in the attrs.xml to allow the user to input a colour, and if the user enters one, then you have to generate random colours around it. For example if someone enters #FF0000, then the random colours that the current `getRandomColor()` function generates must be close to red. `getRandomColor()` is defined in `BarView.java`. If the user does not enter anything in this attribute, then the `getRandomColor()` function would work like it normally does, generating completely random color.

**Comment by krharsh17** [comment]
@VibhorChinda What's the status on this?

**Comment by Sourish-Mukherjee** [comment]
I would like to work on this issue, if there are no updates.

**Comment by VibhorChinda** [comment]
I am working on it and will soon send a PR. Sorry for late response was busy with university exams but now i am free.

**Comment by LuGO0** [comment]
@krharsh17  can I take this one up if @VibhorChinda  is not continuing on this .

**Comment by krharsh17** [comment]
@VibhorChinda what's the status on this?

**Comment by dino-saurabh** [comment]
can I take it up?? @krharsh17

**Comment by krharsh17** [comment]
This has been inactive for too long. I'm afraid I'll have to reassign this now.
