### ISSUE TITLE
Add a listener for click event on bars

### ISSUE THREAD

**Issue by krharsh17** [krharsh17/barview-android#22]
The user should be able to attach the listener by calling `barViewObject.addOnClickListener()` and the listener should have an argument `index` which would contain the index of the bar that has been clicked.

**Comment by RaghavAwasthi** [comment]
Hey can you assign me on this

**Comment by krharsh17** [comment]
Sure!

**Comment by ranjal007** [comment]
I need to work on this issue. Please assign it to me.

**Comment by meghaa105** [comment]
I would like to work on this issue

**Comment by RaghavAwasthi** [comment]
I am already assigned to this one and most of the work is done
