### ISSUE TITLE
Option to set a background color for the entire barview

### ISSUE THREAD

**Issue by krharsh17** [krharsh17/barview-android#23]
Include an attribute in the xml tag of the library to directly specify a background colour. Alternatively, define a `setBackgroundColor(Color color)` function in the library to allow dynamic modification of the background color.

**Comment by BhuwanChandra** [comment]
@krharsh17 I would like to work on it.

**Comment by krharsh17** [comment]
@BhuwanChandra I've assigned it to you

**Comment by vinay2214** [comment]
I would like to work on it

**Comment by krharsh17** [comment]
@vinay2214 I've already assigned it to @BhuwanChandra
