### ISSUE TITLE
[DOCUMENTATION] Write proper documentation for all library functions

### ISSUE THREAD

**Issue by krharsh17** [krharsh17/barview-android#24]

**Comment by dino-saurabh** [comment]
Can you please provide some description and scope !!.

**Comment by krharsh17** [comment]
There are a few functions and variables defined throughout the library module. You need to write documentation for those. You can refer to [this](https://www.spiria.com/en/blog/method-and-best-practices/how-document-java-code/) to know more about how to write documentation for java.

**Comment by rasacharjee** [comment]
I want to work on the issue

**Comment by dino-saurabh** [comment]
Mee too😅!!

**Comment by Angelvicks** [comment]
Please i will like to work on this isssue

**Comment by ParichayDey8** [comment]
I want to work on this issue

**Comment by Akansha2202** [comment]
i want to work on this issue

**Comment by krharsh17** [comment]
Since this is a beginner-friendly issue, and @LuGO0 & @rasacharjee have already gotten a chance, so I'm gonna assign it to @Angelvicks who can make good use of this issue to start their open source journey. I hope you guys don't mind😄 More issues will be coming soon ✌️

**Comment by krharsh17** [comment]
This same issue will be raised again at the end of this month to update the documentation and will be raised once every month till the end of GSSoC, so others can take it up then.

**Comment by Angelvicks** [comment]
Ok thanks @krharsh17 am working on it

**Comment by Angelvicks** [comment]
Please what is the deadline to submit the documentation?

**Comment by Riyagoel2** [comment]
I also want to work on this issue @krharsh17

**Comment by vikasgola** [comment]
@Angelvicks update your progress here.

**Comment by Angelvicks** [comment]
I received details on my work by @krharsh17 so am working on it.

**Comment by krharsh17** [comment]
@Angelvicks How much more time are going to need for this?

**Comment by Angelvicks** [comment]
I am sorry for taking long. @krharsh17  I will unassign myself

**Comment by dino-saurabh** [comment]
Can I get this @krharsh17 I had the first comment on this thread😀

**Comment by sidhuparas** [comment]
@LuGO0 Go ahead :) Be sure to communicate with us on Slack for the documentation format.

**Comment by dino-saurabh** [comment]
As @krharsh17  had insisted I will use [this](https://www.spiria.com/en/blog/method-and-best-practices/how-document-java-code/) as a convention.
