### ISSUE TITLE
Add shadow behind each bar of the same color as the bar

### ISSUE THREAD

**Issue by krharsh17** [krharsh17/barview-android#3]

**Comment by rajkothari634** [comment]
i want to work on it

**Comment by krharsh17** [comment]
Okay, I'll assign this to you

**Comment by rohg007** [comment]
Can I work on this?

**Comment by 8426988382** [comment]
@krharsh17 ,I would like to work on this.

**Comment by ranjal007** [comment]
I need to work on this issue. Please assign it to me.

**Comment by dino-saurabh** [comment]
@rajkothari634 are you still working on this ??

**Comment by vikasgola** [comment]
@rajkothari634 Update your progress here.

**Comment by ranjal007** [comment]
I need to work on this issue . please assign it to me for GSSOC 20

**Comment by vikasgola** [comment]
@ranjal007, let @rajkothari634 provide update on the issue who has been assigned. In case, there is no progress, you may be assigned.

**Comment by ranjal007** [comment]
Okay I will be waiting for it.

**Comment by rajkothari634** [comment]
@ranjal007 I have completed my work I just need to do some customisation and I will create pull request it will take 2 days maximum.
