### ISSUE TITLE
bar-android does not have splash screen 

### ISSUE THREAD

**Issue by sg28march** [krharsh17/barview-android#37]
**Is your feature request related to a problem? Please describe.**
 No
**Describe the solution you'd like**
A splash screen can be added to improve the first user experience with the app.

**Comment by sg28march** [comment]
I want to work on this issue

**Comment by krharsh17** [comment]
Where exactly do you want to put a splash screen?

**Comment by sg28march** [comment]
> Where exactly do you want to put a splash screen?
when the app starts splash screen will be displayed for few seconds and then the main layout will be 
displayed .

**Comment by krharsh17** [comment]
I don't think that's needed for a library project. So I'm gonna have to close this one.
