### ISSUE TITLE
Allow the use of local fonts stored in target app's fonts folder in the library

### ISSUE THREAD

**Issue by krharsh17** [krharsh17/barview-android#4]
~The fonts have to be discussed with the mentors before being put into the project.~

~The ttf or otf files for each selected font has to be included in the project and an xml attribute has to be defined which can allow devs to choose from the available list of fonts.~

Use the target app's fonts in the library with the help of @FontRes annotations. Also make sure to remove the files currently stored in the library's fonts folder.

**Comment by prince-09** [comment]
I want to work on it.

**Comment by krharsh17** [comment]
Sure. Just discuss over this with the mentors before beginning
