### ISSUE TITLE
Allow the use of local colors of app in color.xml folder of app.

### ISSUE THREAD

**Issue by prince-09** [krharsh17/barview-android#50]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

We should allow users to use the local colors from the color.xml folder of the app.

**Additional context**

**Comment by prince-09** [comment]
Can I work on this issue?

**Comment by saumya1singh** [comment]
Hey @prince-09  ! Can you clearly describe the issue ? Do you want to add some particular colors in color.xml that should be used everytime ?

**Comment by prince-09** [comment]
Yes If user has some colours in color.xml then he should be able to choose that colour by @color/xyz like we have in text view or edittext.

**Comment by krharsh17** [comment]
Isn't it possible with the current code in the library?

**Comment by prince-09** [comment]
no, it is not possible with the current code.

**Comment by saumya1singh** [comment]
@prince-09 so basically you want to add some hex codes of colors in color.xml file?
I am not sure if I got your point correctly?
cc @krharsh17

**Comment by saumya1singh** [comment]
Clarify the issue here and if seems good it will be assigned to you! @prince-09

**Comment by krharsh17** [comment]
Yeah, I too don't seem to fully understand the issue, maybe some examples might help? @prince-09

**Comment by prince-09** [comment]
![Screenshot (190)](https://user-images.githubusercontent.com/52371330/77575696-f08e6f80-6ef9-11ea-80a1-8bd0d720f4a5.png)
![Screenshot (191)](https://user-images.githubusercontent.com/52371330/77575702-f421f680-6ef9-11ea-8508-b3ca304e5db5.png)
In background attribute we have @color/colorPrimary option... but we are not getting it in labelTextcolor attribute.

**Comment by krharsh17** [comment]
Alright, please make a fix for it!

**Comment by krharsh17** [comment]
What's the status on this @prince-09 ?
