### ISSUE TITLE
Feature: Automatic Bumping of Dependencies

### ISSUE THREAD

**Issue by RaghavAwasthi** [krharsh17/barview-android#51]
**Is your feature request related to a problem? Please describe.**
We need to have automatic Dependency Upgrading tool activated to facilitate better feature updates offered by newer versions of Library 

**Describe the solution you'd like**
We need to enable a program called Dependabot available in Github MarketPlace 
https://github.com/marketplace/dependabot-preview

**Comment by ShivangiSingh17** [comment]
Go ahead @RaghavAwasthi
