### ISSUE TITLE
Delete a Bar on Long Click after showing an Alert Dialogue.

### ISSUE THREAD

**Issue by Alaska18** [krharsh17/barview-android#54]
**Describe the solution you'd like**
A bar will get deleted by clicking on "yes" in an Alert dialogue Box which will appear after long Click on the selected Bar.
I want to work on this issue.

**Comment by ShivangiSingh17** [comment]
Go Ahead @Alaska18!!

**Comment by dino-saurabh** [comment]
@Alaska18 would you please implement the delete action using the swipe gesture instead of long press !! because I feel long press is used in most of the apps for like adjustment #73

**Comment by Alaska18** [comment]
Thanks for the feedback! I will consider this.

**Comment by Akansha2202** [comment]
I would like to work on it

**Comment by srijande** [comment]
assign me
