### ISSUE TITLE
Create 'expand' intro animation option

### ISSUE THREAD

**Issue by krharsh17** [krharsh17/barview-android#6]
Here's how the intro animation should look:

![Preview](https://i.imgur.com/ox6FmMe.gif)

Also, include an attribute to specify animation duration in ms

**Comment by parthsharma07** [comment]
I want to work on this issue. Please assign it to me.

**Comment by krharsh17** [comment]
Sure

**Comment by 8426988382** [comment]
I would like to work on this. @krharsh17  Please assign it to me.
