### ISSUE TITLE
Add Pull Request Template

### ISSUE THREAD

**Issue by Aman-Codes** [krharsh17/barview-android#70]
**Is your feature request related to a problem? Please describe.**
Currently no pull request template is available in this project.

**Describe the solution you'd like**
@krharsh17 I am a GSSOC participant and I would like to add a pull_request_template.md file in this project.

**Additional context**
### Pull request
![pull request](https://user-images.githubusercontent.com/54680709/77219319-c97f1900-6b5a-11ea-9bd3-a45fcaea4842.PNG)

**Comment by krharsh17** [comment]
Sure, please go ahead✌🏻

**Comment by dino-saurabh** [comment]
@krharsh17 I guess we should have a template but it should be reasonable and not which anybody wont fill out !! we should consider removing some options from the current proposed template!!

**Comment by Aman-Codes** [comment]
@LuGO0 Thanks for your valuable feedback. Would love to know which options do you want to remove ?
I think proposed changes and types of changes should not cause a problem.
Screenshots and other information section can be optional for participants to add if they wish to.
Checklist was added just to ensure that the participants review their changes properly before making a pull request. Thus it may ease out the process of reviewing by the mentors.

If still mentors want any changes in it then would definitely do it.
