### ISSUE TITLE
Remove all log lines

### ISSUE THREAD

**Issue by krharsh17** [krharsh17/barview-android#8]

**Comment by Medhavi-16** [comment]
I am interested in doing this.

**Comment by krharsh17** [comment]
Okay. I'll assign this to you. But make sure to create a PR after 1st March so that it can get counted in GSSoC.

**Comment by shreyasrivastava936** [comment]
Hi! I would like to work on this issue. please assign this task to me for GSSoC'20.

**Comment by raksha009** [comment]
Hii! What are log lines !?

**Comment by akshaydhiran** [comment]
I am interested in working on this issue.

**Comment by krharsh17** [comment]
This issue is already assigned to a participant currently
