### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by Sapna2001** [krharsh17/barview-android#87]
Readme can be updated with details of mentors,admins,slack channels and details of gssoc. Please assign me this issue.

**Comment by krharsh17** [comment]
Could you please list the details that you would like to add to the README here first?

**Comment by Sapna2001** [comment]
I would like to add the following details:-
1. Tech stacks used.
2. Details of mentors and admin with their Github and LinkedIn URL.
3.The vision of the project.

**Comment by spacemonkey1101** [comment]
Hello 
- I would like to add useful links for setting up android and basics of github
-System Requirements

**Comment by krharsh17** [comment]
@Sapna2001 Actually a project of this kind does not need to have the details that you have mentioned, so I'll have to close this issue. You can always look for bugs in the current code, or suggest new features for the library 🙂
