### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by spacemonkey1101** [krharsh17/barview-android#88]
Add the system requirements for running the app and add a tutorial link for installing android.

**Comment by saumya1singh** [comment]
Hey @spacemonkey1101, I have assigned the task to you! Make sure to follow the issue temp :)

**Comment by saumya1singh** [comment]
@krharsh17 Kindly double check if you need these features in the readme.

**Comment by krharsh17** [comment]
@spacemonkey1101 Please post the changes that you wish to make in the README here before creating a PR.

**Comment by spacemonkey1101** [comment]
Hello @krharsh17 and @SaumyaSingh1 , first of all I would like to apologize for not being able to comment here earlier. 

I would like to add  these things:-

Learning Resources
- https://developer.android.com/studio/install
- https://try.github.io/

System Requirements
- Git
- Android Studio

**Comment by krharsh17** [comment]
Alright, go ahead!
