### ISSUE TITLE
Broken link in the contributing.md file

### ISSUE THREAD

**Issue by Aman-Codes** [krharsh17/barview-android#89]
**Describe the bug**
The link to .appveyor.yml is broken link in the contributing.md file. As a GSSOC participant I would like to update it.

**Comment by sidhuparas** [comment]
Hi there, how will you fix it?

**Comment by Aman-Codes** [comment]
I am thinking of removing that line as currently there is no .appveyor.yml file in the repository. It can be added later once the file is created.

**Comment by sidhuparas** [comment]
Well, I think @krharsh17 can specify more accurately if that line has to be removed or other changes need to be made.

**Comment by krharsh17** [comment]
I don't think we should remove that. It had to be updated when we shifted from AppVeyor to Travis, but was missed. We'll have to use https://github.com/krharsh17/barview-android/blob/develop/.travis.yml there. Thanks @Aman-Codes for pointing it out.

**Comment by krharsh17** [comment]
Also, @Aman-Codes instead of making a PR just for one single change, I'll suggest that you go through all the doc files thoroughly and fix all broken links/typos/wrong content and then make a PR.

**Comment by Aman-Codes** [comment]
Found a typo in contributing.md in the app section the name of project should be barview
![Screenshot_20200429-173739_1](https://user-images.githubusercontent.com/54680709/80594480-b22c2900-8a40-11ea-8dea-da39bfd11b08.jpg)

**Comment by sidhuparas** [comment]
@Aman-Codes Cool. See if you can find more. Make a PR when your search completes.

**Comment by Aman-Codes** [comment]
I think it would be nice if we add a link to Gssoc site in readme.md
![Screenshot_20200429-180107_1](https://user-images.githubusercontent.com/54680709/80603119-9bd89a00-8a4d-11ea-8019-82f9455de500.jpg)
@krharsh17 @sidhuparas what are your views?

**Comment by sidhuparas** [comment]
@Aman-Codes Yeah, it's do-able.

**Comment by Aman-Codes** [comment]
@sidhuparas @krharsh17 I have made a pull request please review it.

**Comment by sidhuparas** [comment]
@Aman-Codes, give me some time. I will review on this weekend.
