### ISSUE TITLE
Replace all inline static occurences of default values for variables with static variables, which have to be defined in a separate interface named Constants

### ISSUE THREAD

**Issue by krharsh17** [krharsh17/barview-android#9]
For example in such a case
```
.
.

            if(LABEL_TEXT_COLOR == null)
                LABEL_TEXT_COLOR = "#424242";
            if(VALUE_TEXT_COLOR == null)
.
.
```
Replace the static string "#424242" with a static string variable declared in a seperate interface by the name `Constants`

**Comment by Sourish-Mukherjee** [comment]
So basically we need to create an **Interface** for defining all the constants and instead use the interface's variable instead of direct constants? #GSSOC20

**Comment by krharsh17** [comment]
@Sourish-Mukherjee Yes exactly

**Comment by rasacharjee** [comment]
I want to take the issue

**Comment by Sourish-Mukherjee** [comment]
Will be a good experience for me, I want to take the issue

**Comment by krharsh17** [comment]
I'll assign this to @Sourish-Mukherjee as #7 is already assigned to @rasacharjee
