### ISSUE TITLE
Remove redundant toast on click

### ISSUE THREAD

**Issue by krharsh17** [krharsh17/barview-android#92]
**Describe the bug**
A toast "Bar at position x" appears when you click on the bars.

**To Reproduce**
Click on a bar

**Expected behaviour**
No toast should appear

**Comment by sumanthst24** [comment]
would like to work on this issue

**Comment by sumanthst24** [comment]
Could you assign this issue to me @krharsh17

**Comment by sidhuparas** [comment]
@sumanthst24 Any update on this?

**Comment by sidhuparas** [comment]
This is up-for-grabs. @sumanthst24 has some personal issues so if anyone else wants to take it.

**Comment by Alaska18** [comment]
I would like to work on this issue.

**Comment by sidhuparas** [comment]
@Alaska18 Go ahead!
